### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined in SpatialPooler.js

### ISSUE THREAD

**Issue by jefffohl** [iandanforth/nupic-js#13]
This happens when an input vector is not defined.

**Comment by iandanforth** [comment]
Would you like an assert error instead?

**Comment by jefffohl** [comment]
I added some checks in the compute() function to handle unexpected input. Also, I made a tweak to the animate() function in index.html to prevent the compute() function from being called until the proper time. Let me know if you think there is a better way to address this.

**Comment by iandanforth** [comment]
Actually. I think I've fixed this locally. What should happen is a compute() call with an empty / otherwise invalid input is a no-op. It just returns. My reasoning here is that I don't want to force users of SpatialPooler to guarantee load time before calling compute(). If you want to embed the call in a onReady style callback, that's fine. But I want it to be callable even before assets are loaded.

**Comment by jefffohl** [comment]
OK, so it would be better to remove the adjustment I made to index.html (and possibly replace with some jQuery), but leave what I added to SpatialPooler.js?

**Comment by jefffohl** [comment]
Or, would it be better to withdraw my pull request, and replace with a PR you have waiting?

**Comment by iandanforth** [comment]
Nevermind, your changes are good and I didn't have a local fix for this (was a diff issue I was thinking of). I've merged your PR. Thanks again!
